INSERT INTO games
    (id, name, normalized_id, image, description, price, release_date, user_rating, developer, publisher, has_discount, age_rating)
VALUES
    (1, 'The Witcher 3: Wild Hunt', 'the-witcher-3-wild-hunt-cd-projekt-red', 'https://cdn.example.com/games/the-witcher-3-wild-hunt.jpg', 'A vast open-world fantasy RPG following Geralt of Rivia through war-torn kingdoms and monster contracts.', 39.99, '2015-05-19 00:00:00.000000', 9.7, 'CD Projekt Red', 'CD Projekt', false, 'EIGHTEEN'),
    (2, 'Elden Ring', 'elden-ring-fromsoftware', 'https://cdn.example.com/games/elden-ring.jpg', 'An open-world action RPG set in the Lands Between, blending challenging combat with expansive exploration.', 59.99, '2022-02-25 00:00:00.000000', 9.6, 'FromSoftware', 'Bandai Namco Entertainment', false, 'SIXTEEN'),
    (3, 'Baldur''s Gate 3', 'baldurs-gate-3-larian-studios', 'https://cdn.example.com/games/baldurs-gate-3.jpg', 'A party-based role-playing game inspired by tabletop adventures, with deep choices and tactical encounters.', 59.99, '2023-08-03 00:00:00.000000', 9.8, 'Larian Studios', 'Larian Studios', false, 'SIXTEEN'),
    (4, 'Cyberpunk 2077', 'cyberpunk-2077-cd-projekt-red', 'https://cdn.example.com/games/cyberpunk-2077.jpg', 'A futuristic open-world RPG set in Night City, centered on mercenary work, cyberware, and corporate power.', 59.99, '2020-12-10 00:00:00.000000', 8.8, 'CD Projekt Red', 'CD Projekt', true, 'EIGHTEEN'),
    (5, 'Final Fantasy VII Remake', 'final-fantasy-vii-remake-square-enix', 'https://cdn.example.com/games/final-fantasy-vii-remake.jpg', 'A modern reimagining of the Midgar chapter, combining cinematic storytelling with real-time RPG combat.', 49.99, '2020-04-10 00:00:00.000000', 8.9, 'Square Enix', 'Square Enix', false, 'TWELVE'),
    (6, 'Persona 5 Royal', 'persona-5-royal-atlus', 'https://cdn.example.com/games/persona-5-royal.jpg', 'A stylish turn-based RPG about students balancing daily life, friendships, and supernatural palace heists.', 59.99, '2019-10-31 00:00:00.000000', 9.4, 'Atlus', 'Atlus', true, 'SIXTEEN'),
    (7, 'Doom Eternal', 'doom-eternal-id-software', 'https://cdn.example.com/games/doom-eternal.jpg', 'A fast-paced first-person shooter built around aggressive movement, resource management, and demon-slaying arenas.', 39.99, '2020-03-20 00:00:00.000000', 9.0, 'id Software', 'Bethesda Softworks', false, 'EIGHTEEN'),
    (8, 'Halo Infinite', 'halo-infinite-343-industries', 'https://cdn.example.com/games/halo-infinite.jpg', 'A sci-fi first-person shooter following Master Chief across a large ringworld with classic arena combat.', 59.99, '2021-12-08 00:00:00.000000', 8.4, '343 Industries', 'Xbox Game Studios', true, 'SIXTEEN'),
    (9, 'Counter-Strike 2', 'counter-strike-2-valve', 'https://cdn.example.com/games/counter-strike-2.jpg', 'A tactical competitive first-person shooter focused on precision gunplay, economy decisions, and team coordination.', 0.00, '2023-09-27 00:00:00.000000', 8.1, 'Valve', 'Valve', false, 'SIXTEEN'),
    (10, 'Resident Evil 4', 'resident-evil-4-capcom', 'https://cdn.example.com/games/resident-evil-4.jpg', 'A survival horror action game following Leon Kennedy through a hostile rural village and terrifying encounters.', 59.99, '2023-03-24 00:00:00.000000', 9.3, 'Capcom', 'Capcom', false, 'EIGHTEEN'),
    (11, 'Dead Space', 'dead-space-motive-studio', 'https://cdn.example.com/games/dead-space.jpg', 'A science-fiction survival horror remake set aboard the USG Ishimura with tense exploration and dismemberment combat.', 59.99, '2023-01-27 00:00:00.000000', 8.9, 'Motive Studio', 'Electronic Arts', true, 'EIGHTEEN'),
    (12, 'Silent Hill 2', 'silent-hill-2-konami', 'https://cdn.example.com/games/silent-hill-2.jpg', 'A psychological survival horror classic about grief, guilt, and unsettling discoveries in the town of Silent Hill.', 29.99, '2001-09-24 00:00:00.000000', 9.2, 'Konami', 'Konami', false, 'EIGHTEEN'),
    (13, 'EA Sports FC 24', 'ea-sports-fc-24-ea-vancouver', 'https://cdn.example.com/games/ea-sports-fc-24.jpg', 'A football simulation featuring licensed clubs, career modes, online play, and squad-building progression.', 69.99, '2023-09-29 00:00:00.000000', 7.6, 'EA Vancouver', 'Electronic Arts', true, 'GENERAL_AUDIENCE'),
    (14, 'NBA 2K24', 'nba-2k24-visual-concepts', 'https://cdn.example.com/games/nba-2k24.jpg', 'A basketball simulation with team play, career progression, online competition, and presentation inspired by the NBA.', 69.99, '2023-09-08 00:00:00.000000', 7.1, 'Visual Concepts', '2K', true, 'GENERAL_AUDIENCE'),
    (15, 'Rocket League', 'rocket-league-psyonix', 'https://cdn.example.com/games/rocket-league.jpg', 'A competitive sports game where rocket-powered cars play high-speed soccer in arenas built for aerial plays.', 0.00, '2015-07-07 00:00:00.000000', 8.7, 'Psyonix', 'Psyonix', false, 'GENERAL_AUDIENCE'),
    (16, 'League of Legends', 'league-of-legends-riot-games', 'https://cdn.example.com/games/league-of-legends.jpg', 'A competitive MOBA where teams of champions battle across Summoner''s Rift with objectives, lanes, and team fights.', 0.00, '2009-10-27 00:00:00.000000', 8.5, 'Riot Games', 'Riot Games', false, 'TWELVE'),
    (17, 'Dota 2', 'dota-2-valve', 'https://cdn.example.com/games/dota-2.jpg', 'A deep competitive MOBA centered on hero drafts, itemization, map control, and high-stakes team strategy.', 0.00, '2013-07-09 00:00:00.000000', 8.9, 'Valve', 'Valve', false, 'TWELVE'),
    (18, 'Heroes of the Storm', 'heroes-of-the-storm-blizzard-entertainment', 'https://cdn.example.com/games/heroes-of-the-storm.jpg', 'A team-focused MOBA that brings Blizzard characters together across varied battlegrounds with shared progression.', 0.00, '2015-06-02 00:00:00.000000', 7.9, 'Blizzard Entertainment', 'Blizzard Entertainment', false, 'TWELVE'),
    (19, 'XCOM 2', 'xcom-2-firaxis-games', 'https://cdn.example.com/games/xcom-2.jpg', 'A tactical turn-based strategy game about leading a resistance force against alien occupation on Earth.', 49.99, '2016-02-05 00:00:00.000000', 8.8, 'Firaxis Games', '2K', true, 'SIXTEEN'),
    (20, 'Civilization VI', 'civilization-vi-firaxis-games', 'https://cdn.example.com/games/civilization-vi.jpg', 'A turn-based strategy game about building an empire through science, culture, diplomacy, conquest, and exploration.', 59.99, '2016-10-21 00:00:00.000000', 8.6, 'Firaxis Games', '2K', true, 'TWELVE');

INSERT INTO game_genres (game_id, genre)
VALUES
    (1, 'RPG'),
    (2, 'RPG'),
    (3, 'RPG'),
    (3, 'TURN_BASED'),
    (4, 'RPG'),
    (4, 'FPS'),
    (5, 'RPG'),
    (6, 'RPG'),
    (6, 'TURN_BASED'),
    (7, 'FPS'),
    (8, 'FPS'),
    (9, 'FPS'),
    (10, 'SURVIVOR_HORROR'),
    (11, 'SURVIVOR_HORROR'),
    (12, 'SURVIVOR_HORROR'),
    (13, 'SPORT'),
    (14, 'SPORT'),
    (15, 'SPORT'),
    (16, 'MOBA'),
    (17, 'MOBA'),
    (18, 'MOBA'),
    (19, 'TURN_BASED'),
    (20, 'TURN_BASED');
